window = { opacity = 0.9 }

[font]
size = 7.0
[font.normal]
family = "Hack Nerd Font Mono"

[cursor]
style = { shape = "Beam", blinking = "Always" }

[colors.primary]
background = "#0d0c0d"
foreground = "#ababa4"
[colors.cursor]
text = "CellBackground"
cursor = "#b0d0f0"
[colors.normal]
black = "#0d0c0d"
red = "#f2777a"
green = "#99cc99"
yellow = "#d2a853"
blue = "#6699cc"
magenta = "#cc99cc"
cyan = "#66cccc"
white = "#ababa4"
[colors.bright]
black = "#515151"
red = "#ff5f63"
green = "#94ea94"
yellow = "#f0b643"
blue = "#59a2ea"
magenta = "#ea94ea"
cyan = "#59eaea"
white = "#f2f0ec"
